### ISSUE TITLE
Add option to have no gutter when using grid.

### ISSUE THREAD

**Issue by MMasey** [yoyodesign/hako#1]
When using the grid, can we make it possible to have a gutter of 0px.

**Comment by swudged** [comment]
The solution to this is to extend both `hako-grid` and `hako-grid-column` to configure whether the grid and columns should have spacing added. This will be for both column and row spacing. The following shows how the author may achieve this:

```
.media-gallery
    hako-grid({
        columnGap: false // optional, true by default
        rowGap: false // optional, false by default
        columnConfig: {
            selector: ".media-gallery_item"
            columns: { columns: 4 }
         }
    })
```

Alternatively, this could have been written as such:

```
.media-gallery
    hako-grid({ columnGap: false, rowGap: false })

    &__item
        hako-grid-column({ columnGap: false rowGap: false }, { columns: 4 })
```

As column gutters are available by default, the author can add gutters to both axes by doing the following:

```
.media-gallery
    hako-grid({
        rowGap: true
        columnConfig: {
            selector: ".media-gallery_item"
            columns: { columns: 4 }
         }
    })
```

or:

```
.media-gallery
    hako-grid({ rowGap: true })

    &__item
        hako-grid-column({ rowGap: true }, { columns: 4 })
```

If no configuration is needed for column or row gaps, the author can write:

```
.media-gallery
    hako-grid({
        columnConfig: {
            selector: ".media-gallery_item"
            columns: { columns: 4 }
         }
    })
```

or:

```
.media-gallery
    hako-grid()

    &__item
        hako-grid-column({ columns: 4 })
```

The configuration will be limitted to configuring the grid and columns at all breakpoints, as it is yet to be seen if configuring column and or row gaps across breakpoints will be useful. This could change in a future release.

**Comment by swudged** [comment]
In addition, `hako-grid` must be able to allow for multiple grid column configurations. The syntax for doing this would be to wrap the configuration for columns in parentheses, e.g:

```
.media-gallery
    hako-grid({
        columnConfig: {
            selector: ".media-gallery_item"
            columns: ({ columns: 6, to: "smed" } { columns: 4, from: "smed" })
         }
    })
```

**Comment by swudged** [comment]
Because of how arrays and objects work within Stylus, 1.0.0-beta.2 added a bug that meant grids weren't rendered correctly. This is because rest parameters were being used for `hako-grid-column`, and `hako-grid` was using a list of objects. The two types appear to be inconsistent in their manner.

The hako-grid mixin will be updated to be used as such:

```
.media-gallery
    hako-grid({
        columnGap: false
        rowGap: true
        columnSelector: ".media-gallery__item"
        columns: ({ columns: 6, to: "smed" } { columns: 4, from: "smed" })
    })
```

This configuration can also work like so:

```
.media-gallery
    hako-grid()

    &__item
        hako-grid-column({ columnGap: false, rowGap: true }, ({ columns: 6, to: "smed" } { columns: 4, from: "smed" }))
```

In no configuration is needed for column or row gaps, the following will work:

```
.media-gallery
    hako-grid({
        columnSelector: ".media-gallery__item"
        columns: ({ columns: 6, to: "smed" } { columns: 4, from: "smed" })
    })
```

Or:

```
.media-gallery
    hako-grid()

    &__item
        hako-grid-column(({ columns: 6, to: "smed" } { columns: 4, from: "smed" }))
```

The `columnConfig` object that was previously used with the grid configuraton object has been removed for simplicity.
